language: go
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -service=travis-ci
go_import_path: github.com/pdupub/go-pdu
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./crypto/pdu
        - go test ./crypto/ethereum
        - go test ./crypto/bitcoin
        - go test ./dag
        - go test ./core

    - os: linux
      dist: xenial
      sudo: required
      go: 1.13.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./crypto/pdu
        - go test ./crypto/ethereum
        - go test ./crypto/bitcoin
        - go test ./dag
        - go test ./core

    - os: osx
      go: 1.13.x
      script:
        - make install
        - GO111MODULE=on
        - go test ./crypto/pdu
        - go test ./crypto/ethereum
        - go test ./crypto/bitcoin
        - go test ./dag
        - go test ./core
