language: go
go_import_path: github.com/pdupub/PDU
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.9.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test

    - os: linux
      dist: trusty
      sudo: required
      go: 1.10.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test

    - os: linux
      dist: trusty
      sudo: required
      go: 1.11.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go run build/ci.go install
        - go run build/ci.go test

