language: go
go_import_path: github.com/pdupub/go-pdu
sudo: false
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - sudo modprobe fuse
        - sudo chmod 666 /dev/fuse
        - sudo chown root:$USER /etc/fuse.conf
        - go get github.com/ethereum/go-ethereum
        - go get github.com/btcsuite/btcd
        - make install
        - go test ./crypto/pdu
        - go test ./dag
        - go test ./core

